title: Alertme
author: RDA
email: layne@rdacorp.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation on the Alertme service

github_username:  layne1990

sass:
    style: compressed

header_pages:
 - getting-started.md
 - pricing.md

markdown: kramdown
highlighter: rouge

